CREATE TABLE PUBLIC.TEMPLATE
(
    TEMPLATE_ID IDENTITY     NOT NULL,
    OS_TYPE     VARCHAR(100) NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    FILENAME    VARCHAR(400) NOT NULL,
    SIZE        BIGINT       NOT NULL
);
CREATE SEQUENCE PUBLIC.SEQ_TEMPLATE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PUBLIC.NODE
(
    NODE_ID     IDENTITY      NOT NULL,
    HOSTNAME    VARCHAR(400)  NOT NULL,
    PORT        VARCHAR(20)   NOT NULL,
    START_TIME  TIMESTAMP     NOT NULL,
    LAST_PING   TIMESTAMP     NOT NULL
);
CREATE SEQUENCE PUBLIC.SEQ_NODE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PUBLIC.MACHINE
(
    MACHINE_ID       IDENTITY      NOT NULL,
    TEMPLATE_ID      INTEGER       NOT NULL,
    NODE_ID          INTEGER,
    NAME             VARCHAR(400)  NOT NULL,
    STATE            VARCHAR(20)   NOT NULL,
    UUID             VARCHAR(36),
    BOOTABLE_MEDIUM  VARCHAR(400),
    VBOX_UUID        VARCHAR(36),
    FOREIGN KEY(TEMPLATE_ID) REFERENCES PUBLIC.TEMPLATE(TEMPLATE_ID),
    FOREIGN KEY(NODE_ID)     REFERENCES PUBLIC.NODE(NODE_ID)
);
CREATE SEQUENCE PUBLIC.SEQ_MACHINE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PUBLIC.TASK
(
    TASK_ID       IDENTITY     NOT NULL,
    STATUS        VARCHAR(20)  NOT NULL,
    TYPE          VARCHAR(20)  NOT NULL,
    SCHEDULE_TIME TIMESTAMP    NOT NULL
);
CREATE SEQUENCE PUBLIC.SEQ_TASK_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PUBLIC.TASK_PARAM
(
    TASK_ID       INTEGER       NOT NULL,
    NAME          VARCHAR(20)   NOT NULL,
    VALUE         VARCHAR(20),
    FOREIGN KEY(TASK_ID) REFERENCES PUBLIC.TASK(TASK_ID),
);

-- create default template
INSERT INTO TEMPLATE (TEMPLATE_ID, OS_TYPE, NAME, FILENAME, SIZE) 
     VALUES ((VALUES NEXT VALUE FOR SEQ_TEMPLATE_ID), 'Ubuntu', 'Ubuntu minimal config', 'ubuntu-light.vdi', 1073741824);
     
-- create default virtual machine
INSERT INTO MACHINE (MACHINE_ID, TEMPLATE_ID, NAME, STATE) 
     VALUES ((VALUES NEXT VALUE FOR SEQ_MACHINE_ID), 1, 'Ubuntu minimal config', 'DONE');